"""Quick test to see which symbol formats Fyers accepts"""
import logging
from src.config import load_config
from src.fixed_improved_websocket import improved_market_data_websocket
import time

logging.basicConfig(level=logging.INFO)

config = load_config()

# Test Nov 25 expiry (nearest expiry - should work)
test_symbols_nov25 = [
    "NSE:NIFTY25NOV25000CE",   # Format being generated by code
]

# Test Dec 02 expiry (next week - might not work yet)
test_symbols_dec02 = [
    "NSE:NIFTY02DEC25000CE",   # Format being generated by validation
]

print("\n" + "="*70)
print("TESTING FYERS SYMBOL ACCEPTANCE")
print("="*70)

print("\n[1] Testing Nov 25 expiry (nearest expiry)...")
print("-"*70)
for symbol in test_symbols_nov25:
    print(f"\nTesting: {symbol}")
    ws = improved_market_data_websocket(
        symbols=[symbol],
        callback_handler=None,
        debug=False
    )
    
    if ws:
        time.sleep(2)
        if hasattr(ws, 'connection_status'):
            status = ws.connection_status
            if status.get('subscribed') == True:
                print(f"✅ ACCEPTED: {symbol}")
            else:
                print(f"❌ REJECTED: {symbol}")
                if 'subscription_error' in status:
                    print(f"   Error: {status['subscription_error']}")
        
        if hasattr(ws, 'close_connection'):
            ws.close_connection()
    else:
        print(f"❌ CONNECTION FAILED")

print("\n[2] Testing Dec 02 expiry (next week)...")
print("-"*70)
for symbol in test_symbols_dec02:
    print(f"\nTesting: {symbol}")
    ws = improved_market_data_websocket(
        symbols=[symbol],
        callback_handler=None,
        debug=False
    )
    
    if ws:
        time.sleep(2)
        if hasattr(ws, 'connection_status'):
            status = ws.connection_status
            if status.get('subscribed') == True:
                print(f"✅ ACCEPTED: {symbol}")
            else:
                print(f"❌ REJECTED: {symbol}")
                if 'subscription_error' in status:
                    print(f"   Error: {status['subscription_error']}")
        
        if hasattr(ws, 'close_connection'):
            ws.close_connection()
    else:
        print(f"❌ CONNECTION FAILED")

print("\n" + "="*70)
print("TEST COMPLETE")
print("="*70)
